<a href="https://colab.research.google.com/github/piyush-raj04/Python/blob/main/numpyarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python-Numpy-Array


In [1]:
import numpy as np

In [4]:
lst=[1,2,3,4]
arr=np.array(lst)



In [6]:
type(arr)

numpy.ndarray

In [8]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [9]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr1.shape

(3, 5)

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
arr[3]

np.int64(4)

In [13]:
arr[3]=5

In [14]:
arr

array([1, 2, 3, 5])

In [16]:
arr[1:3]

array([2, 3])

In [17]:
arr[-1]

np.int64(5)

In [18]:
arr[:-1]

array([1, 2, 3])

In [19]:
arr[::-1]

array([5, 3, 2, 1])

In [20]:
arr[::-2]

array([5, 2])

In [21]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [23]:
arr1[:,1]

array([2, 3, 4])

In [25]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [27]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [28]:
##EDA
arr

array([1, 2, 3, 5])

In [29]:
arr<2

array([ True, False, False, False])

In [30]:
arr[arr<2]

array([1])

In [31]:
arr1.shape

(3, 5)

In [32]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [33]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [35]:
##mechansim to create an array
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [39]:
arr

array([1, 2, 3, 5])

In [40]:
arr *arr

array([ 1,  4,  9, 25])

In [41]:
arr1 *2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [42]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.random.randint(10,50,4)

array([31, 45, 38, 31])

In [46]:
np.random.randint(10,50,4).reshape(2,2)

array([[49, 24],
       [30, 12]])

In [47]:
np.random.randn(5,6)

array([[ 1.00886091,  2.1478882 , -0.37286091, -0.54386946,  0.85067981,
         0.06179532],
       [ 0.14577481, -0.54744681, -1.59877698, -1.22282777,  1.03916908,
         1.02334861],
       [ 0.75935043,  1.12607949,  1.11408234,  0.36695724, -0.11092545,
        -0.17003152],
       [ 0.18611427, -0.23938037, -1.02893235, -1.0374146 ,  1.96535656,
        -0.54896731],
       [-1.47214559, -0.9718154 ,  0.54438441,  0.73037651, -1.11697484,
         0.48222612]])

In [48]:
np.random.random_sample((4,7))

array([[0.7321473 , 0.22183405, 0.82184277, 0.4594202 , 0.12032624,
        0.75862136, 0.59921486],
       [0.04574451, 0.76696986, 0.44495162, 0.87639907, 0.34250854,
        0.68097481, 0.51714772],
       [0.76802798, 0.11359776, 0.25475063, 0.13400136, 0.68807743,
        0.10239295, 0.69101942],
       [0.75758871, 0.05355394, 0.8389566 , 0.71145256, 0.0013304 ,
        0.43729084, 0.04533125]])