<a href="https://colab.research.google.com/github/piyush-raj04/Python/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Pandas

In [2]:
import pandas as pd
import numpy as np

In [4]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [13]:
## Create data frames
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1","Row2","Row3","Row4","Row5"],columns=["Column1","Column2","Column3","Column4"])

In [14]:
df.head()

,Column1,Column2,Column3,Column4
Row1,0,1,2,3
Row2,4,5,6,7
Row3,8,9,10,11
Row4,12,13,14,15
Row5,16,17,18,19


In [15]:
df.tail()

,Column1,Column2,Column3,Column4
Row1,0,1,2,3
Row2,4,5,6,7
Row3,8,9,10,11
Row4,12,13,14,15
Row5,16,17,18,19


In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [18]:
df.describe()

,Column1,Column2,Column3,Column4
count,5.000000,5.000000,5.000000,5.000000
mean,8.000000,9.000000,10.000000,11.000000
std,6.324555,6.324555,6.324555,6.324555
min,0.000000,1.000000,2.000000,3.000000
25%,4.000000,5.000000,6.000000,7.000000
50%,8.000000,9.000000,10.000000,11.000000
75%,12.000000,13.000000,14.000000,15.000000
max,16.000000,17.000000,18.000000,19.000000


In [19]:
##Indexing
##columnname, rowindex[loc],rowindex columnindex number[.iloc]
df.head()

,Column1,Column2,Column3,Column4
Row1,0,1,2,3
Row2,4,5,6,7
Row3,8,9,10,11
Row4,12,13,14,15
Row5,16,17,18,19


In [23]:
type(df['Column1'])

pandas.core.series.Series

In [20]:
df[['Column1','Column2','Column3']]

,Column1,Column2,Column3
Row1,0,1,2
Row2,4,5,6
Row3,8,9,10
Row4,12,13,14
Row5,16,17,18


In [25]:
df.loc[['Row3','Row2']]

,Column1,Column2,Column3,Column4
Row3,8,9,10,11
Row2,4,5,6,7


In [26]:
df.iloc[2:4,0:2]

,Column1,Column2
Row3,8,9
Row4,12,13


In [27]:
df.iloc[2:,1:]

,Column2,Column3,Column4
Row3,9,10,11
Row4,13,14,15
Row5,17,18,19


In [29]:
##to covert into array
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [30]:
##Operations
df.isnull()

,Column1,Column2,Column3,Column4
Row1,False,False,False,False
Row2,False,False,False,False
Row3,False,False,False,False
Row4,False,False,False,False
Row5,False,False,False,False


In [31]:
df['Column3'].unique()

array([ 2,  6, 10, 14, 18])

In [32]:
df['Column3'].value_counts()

,count
Column3,
2,1
6,1
10,1
14,1
18,1


In [33]:
df>2

,Column1,Column2,Column3,Column4
Row1,False,False,False,True
Row2,True,True,True,True
Row3,True,True,True,True
Row4,True,True,True,True
Row5,True,True,True,True


In [34]:
df[df['Column1']>2]

,Column1,Column2,Column3,Column4
Row2,4,5,6,7
Row3,8,9,10,11
Row4,12,13,14,15
Row5,16,17,18,19
